# ══════════════════════════════════════════════════════════════════════
#  ~/.zshrc
#  Rule: nothing expensive at startup. Version managers (nvm, jenv,
#  chruby) load on first use, not in every shell.
# ══════════════════════════════════════════════════════════════════════

# ── PATH / env ────────────────────────────────────────────────────────
# All in ~/.zshenv, which non-interactive shells read TOO
# (Emacs scripts, herdr, launchd, `zsh -c`). Don't put it back here.

# ── Prompt ────────────────────────────────────────────────────────────
eval "$(oh-my-posh init zsh --config ~/oh-my-posh-themes/amro.omp.json)"

# ══════════════════════════════════════════════════════════════════════
#  Plugins (antidote), replaces antigen (unmaintained since 2021)
#  List: ~/.zsh_plugins.txt and ~/.zsh_plugins_fpath.txt
#  antidote builds a static file, only rebuilt when the list changes,
#  so startup cost is just a plain `source`.
# ══════════════════════════════════════════════════════════════════════
ANTIDOTE_LIB=/opt/homebrew/opt/antidote/share/antidote/antidote.zsh

_antidote_static() {           # $1 = base name (no extension)
  local txt="$HOME/$1.txt" zsh="$HOME/$1.zsh"
  [[ -f $txt ]] || return 0
  if [[ ! $zsh -nt $txt ]]; then
    [[ -f $ANTIDOTE_LIB ]] && source "$ANTIDOTE_LIB"
    antidote bundle <"$txt" >|"$zsh"
  fi
  source "$zsh"
}

# 1. completion-only plugins (fpath), must come before compinit
_antidote_static .zsh_plugins_fpath

# ── Completions ───────────────────────────────────────────────────────
# Completions generated by the tools themselves (uv, ruff, herdr, jj, mise...)
# that carapace doesn't cover. Must come BEFORE compinit: it doesn't
# re-read fpath once it has run.
# Regenerate with: zsh-completions-refresh
fpath=("${XDG_CONFIG_HOME:-$HOME/.config}/zsh/completions" $fpath)

# Dump is only rechecked once a day, otherwise compinit -C (fast).
autoload -Uz compinit
_zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
if [[ -n ${_zcompdump}(#qN.mh+24) ]]; then
  compinit -d "$_zcompdump"
else
  compinit -C -d "$_zcompdump"
fi
unset _zcompdump

# Custom completions (Azure, k8s, helm...), loaded if present
for _c in az kompose helm kubectl kustomize k3d; do
  [[ -r "$HOME/.oh-my-zsh/custom/$_c.zsh" ]] && source "$HOME/.oh-my-zsh/custom/$_c.zsh"
done
unset _c

# 2. regular plugins, after compinit (fzf-tab needs it)
_antidote_static .zsh_plugins

# 3. completion: coverage (carapace + generated completions), display
#    (fzf-tab and its previews) and inline suggestions. Must come AFTER
#    compinit and AFTER the plugins, see that file's header.
[[ -r "$HOME/.config/zsh/completion.zsh" ]] && source "$HOME/.config/zsh/completion.zsh"

# ══════════════════════════════════════════════════════════════════════
#  Version managers, lazy loaded
#  Before: nvm 593 ms + jenv 153 ms in EVERY shell (every tmux pane).
#  Now: the binary is on PATH right away, and the tool itself only loads
#  on the first call to `nvm` / `jenv` / `chruby`.
# ══════════════════════════════════════════════════════════════════════

# --- Node: PATH right away, lazy nvm ---

_nvm_load() {
  unfunction nvm node npm npx yarn pnpm corepack 2>/dev/null
  [[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
  [[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"
}
nvm()      { _nvm_load; nvm "$@"; }
node()     { _nvm_load; node "$@"; }
npm()      { _nvm_load; npm "$@"; }
npx()      { _nvm_load; npx "$@"; }
yarn()     { _nvm_load; yarn "$@"; }
pnpm()     { _nvm_load; pnpm "$@"; }
corepack() { _nvm_load; corepack "$@"; }

# --- Java: shims are already on PATH, lazy jenv ---
jenv() {
  unfunction jenv
  eval "$(command jenv init -)"
  jenv "$@"
}

# --- Ruby: lazy chruby (auto.sh hooks every `cd`) ---
_chruby_load() {
  unfunction chruby ruby gem bundle rake ruby-install 2>/dev/null
  source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
  source /opt/homebrew/opt/chruby/share/chruby/auto.sh
}
chruby()       { _chruby_load; chruby "$@"; }
ruby()         { _chruby_load; ruby "$@"; }
gem()          { _chruby_load; gem "$@"; }
bundle()       { _chruby_load; bundle "$@"; }
rake()         { _chruby_load; rake "$@"; }
ruby-install() { _chruby_load; ruby-install "$@"; }

# --- Python: lazy pyenv ---
#
# Measured: `eval "$(pyenv init - zsh)"` cost 155 ms in EVERY shell,
# 45% of total startup. Breakdown:
#   98 ms  `command pyenv rehash`, rebuilds all the shims
#   ~40 ms a `bash --norc` subprocess to dedupe PATH
#   ~15 ms sourcing the completions
#
# rehash only matters after installing a Python version or a package
# that drops a script. Paying for it in every herdr pane, every `zsh -c`
# and every subshell is pure waste. Run `pyenv rehash` by hand instead.
#
# Safe because ~/.zshenv already puts "$PYENV_ROOT/shims" first on PATH,
# so python/pip/uv work right away. Only the `pyenv` function (needed for
# `pyenv shell <version>`) has to exist, hence the same trick as nvm/jenv.
#
# One thing `pyenv init` did that we have to copy: it pulls the shims out
# of PATH and puts them back FIRST, ahead of /opt/homebrew/bin. Without
# that, 29 binaries resolve differently (python3, pip3, black, isort,
# flake8, pyright, pydoc3, spark tools). `python3` would silently go from
# 3.10.7 (pyenv) to 3.14.7 (homebrew).
#
# Done here in .zshrc, not .zshenv: same scope `pyenv init` had (only
# interactive shells). Non-interactive shells keep their PATH as before.
#
# Cost: one zsh array op, no subprocess.
path=("$PYENV_ROOT/shims" ${path:#$PYENV_ROOT/shims})

pyenv() {
  unfunction pyenv
  eval "$(command pyenv init - zsh)"
  pyenv "$@"
}

# ══════════════════════════════════════════════════════════════════════
#  mise: INSTALLED BUT NOT ACTIVATED, on purpose (measured)
#  (recommendation #2, 2026-08-22)
# ══════════════════════════════════════════════════════════════════════
#
#  mise replaces pyenv + nvm + jenv + chruby with one tool, no shims,
#  one `mise.toml` or `.tool-versions` per project. That was the plan.
#  But once pyenv went lazy (block above), the numbers flipped:
#
#    cost of `eval "$(mise activate zsh)"`      +30.8 ms per shell
#    gain from dropping the 4 lazy loaders      -0.11 ms total
#    projects with a mise.toml/.tool-versions         0
#
#  So switching now = +30 ms per shell (23% slower than the current
#  130 ms) for zero functional gain. The speed win mise promised was
#  already banked by lazy pyenv (worth 155 ms).
#
#  It wouldn't even take over the two projects that pin Node:
#  `mise settings get idiomatic_version_file_enable_tools` says `[]`,
#  so mise IGNORES .nvmrc, .python-version, .ruby-version and
#  .java-version until you turn them on.
#
#  What's still true for mise: one tool instead of four, one version
#  file per project, auto-switch on cd. Simpler, not faster.
#
#  ── To switch over, whenever ───────────────────────────────────────
#  1. Tell mise about the versions you already use:
#       mise use -g node@24 python@3.10.7 java@temurin-20
#  2. Make it read the existing .nvmrc files (one project on Node 22, one on 20):
#       mise settings set idiomatic_version_file_enable_tools "node,python"
#     NB: one project pins Node 22, which nvm does NOT have installed
#     (only 18, 20, 24). mise would fix that, so would `nvm install 22`.
#  3. Uncomment the line below.
#  4. Then remove the pyenv / nvm / jenv / chruby blocks above, and the
#     nvm glob in ~/.zshenv, or the two systems step on each other
#     (pyenv/jenv shims stay first on PATH).
#  5. Check no binary resolves differently:
#       for b in python python3 pip3 node npm java black isort pyright; do
#         printf '%-10s %s\n' $b "$(command -v $b)"; done
#     29 binaries exist both as a pyenv shim and in homebrew.
#
# eval "$(mise activate zsh)"
#
#  mise still works by hand without activating it:
#    mise ls-remote node · mise install node@22 · mise exec node@22 -- node -v

# conda removed: uv does the job.
# The install is still there (~/miniconda3, 7.9 GB, plus an env).
# To bring it back:   eval "$(~/miniconda3/bin/conda shell.zsh hook)"
# To delete it:       rm -rf ~/miniconda3 ~/.condarc ~/.conda

# ══════════════════════════════════════════════════════════════════════
#  Environment
# ══════════════════════════════════════════════════════════════════════
export MANPAGER="sh -c 'col -bx | bat -l man -p'"


# fzf: one definition, with preview, respects .gitignore
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="
  --height 60% --layout=reverse --border=rounded --margin=1,2
  --preview 'bat --color=always --style=numbers --line-range :300 {} 2>/dev/null || eza --tree --level=2 --icons {}'
  --preview-window 'right:55%:wrap:hidden'
  --bind 'ctrl-/:toggle-preview,ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down'
"

# llvm@11 (2020) build flags removed from global: they hit EVERY build
# (pip, cargo, cgo, npm rebuild). Put them back per project with direnv
# (.envrc) if a build really needs them:
#   export PATH="/opt/homebrew/opt/llvm@11/bin:$PATH"
#   export LDFLAGS="-L/opt/homebrew/opt/llvm@11/lib"
#   export CPPFLAGS="-I/opt/homebrew/opt/llvm@11/include"

# Hadoop removed: /opt/homebrew/Cellar/hadoop/3.3.4 is gone.
# If you reinstall: brew install hadoop && export HADOOP_HOME=/opt/homebrew/opt/hadoop/libexec

[[ -f "$HOME/.ghcup/env" ]] && source "$HOME/.ghcup/env"
[[ -f "$HOME/.local/bin/env" ]] && source "$HOME/.local/bin/env"

# ══════════════════════════════════════════════════════════════════════
#  Keyboard (readline / emacs)
# ══════════════════════════════════════════════════════════════════════
bindkey -e
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^E' end-of-line

# ══════════════════════════════════════════════════════════════════════
#  Aliases & functions
#  In ~/.config/zsh/aliases.zsh (tracked with the rest of the config).
#  `za` to edit it, `zr` to reload the shell.
# ══════════════════════════════════════════════════════════════════════
[[ -r ~/.config/zsh/aliases.zsh ]] && source ~/.config/zsh/aliases.zsh

# ── fzf keybindings: no need for the mouse ────────────────────────────
# zsh widgets -> keys. Ctrl+G = Git, Ctrl+O = Open, Ctrl+P = Project.
_fzf_widget() { zle -I; "$1"; zle reset-prompt; }
fe-widget()   { _fzf_widget fe }   ; zle -N fe-widget
fcd-widget()  { _fzf_widget fcd }  ; zle -N fcd-widget
fbr-widget()  { _fzf_widget fbr }  ; zle -N fbr-widget
fpj-widget()  { _fzf_widget fpj }  ; zle -N fpj-widget
fmod-widget() { _fzf_widget fmod } ; zle -N fmod-widget

bindkey '^O' fe-widget      # Ctrl+O  open a file
bindkey '^G' fbr-widget     # Ctrl+G  switch git branch
bindkey '^P' fpj-widget     # Ctrl+P  jump into a project
bindkey '^F' fcd-widget     # Ctrl+F  change dir
bindkey '^N' fmod-widget    # Ctrl+N  edit a modified file

# ══════════════════════════════════════════════════════════════════════
#  Integrations
# ══════════════════════════════════════════════════════════════════════
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"
[[ -r "$HOME/.config/broot/launcher/bash/br" ]] && source "$HOME/.config/broot/launcher/bash/br"
command -v direnv >/dev/null && eval "$(direnv hook zsh)"

compdef __start_kubectl k 2>/dev/null

# ══════════════════════════════════════════════════════════════════════
#  Banner, once per terminal window
#  (the var is exported, so subshells and tmux panes opened from this
#  session don't show it again)
# ══════════════════════════════════════════════════════════════════════
if [[ -o interactive && -z $FASTFETCH_SHOWN ]] && command -v fastfetch >/dev/null; then
  export FASTFETCH_SHOWN=1
  fastfetch
fi

# ══════════════════════════════════════════════════════════════════════
#  herdr tab startup command
#
#  herdr-open-project creates each tab with HERDR_TAB_CMD in its env,
#  and this is where that command starts.
#
#  Why not herdr-plus's way: it TYPES the command into the fresh shell's
#  prompt and sends Enter. That races and loses regularly: the text
#  shows up before ZLE is ready, or lands mid-redraw and
#  zsh-syntax-highlighting recurses forever (zsh at 100% CPU, prompt
#  frozen, command shown but never run). That's exactly the "just the
#  command and no terminal" symptom. Here there's nothing to type, the
#  var is already there before the first prompt.
#
#  `unset` first: the command gets a clean env and a subshell won't run
#  it again. When it exits it hands back to this shell, so the tab
#  stays usable.
# ══════════════════════════════════════════════════════════════════════
if [[ -o interactive && -n ${HERDR_TAB_CMD:-} ]]; then
  _herdr_tab_cmd=$HERDR_TAB_CMD
  unset HERDR_TAB_CMD
  eval "$_herdr_tab_cmd"
  unset _herdr_tab_cmd
fi
